const fs = require("fs");
const path = require("path");

const domainSkillsData = {
  "Software Engineering / IT": [
    // Core Programming Languages
    "JavaScript", "TypeScript", "Python", "Java", "C++", "C#", "C Language", "Go (Golang)", "Rust", "PHP",
    "Ruby", "Swift", "Kotlin", "Scala", "Dart", "Elixir", "Clojure", "Haskell", "Erlang", "Julia",
    "Perl", "Lua", "R Language", "Visual Basic .NET", "F#", "Groovy", "COBOL", "Fortran", "Assembly x86/x64",
    "ARM Assembly", "VHDL", "Verilog", "SystemVerilog", "Solidity", "Vyper", "Move Language", "Cairo", "Zig",
    "Nim", "OCaml", "Racket", "Scheme", "Common Lisp", "Tcl/Tk", "Ada", "Prolog", "ActionScript", "APL",
    "Objective-C", "Bash Scripting", "PowerShell Scripting", "Zsh", "Awk", "Sed",
    // Frontend Web Development
    "React.js", "Angular", "Vue.js", "Next.js", "Nuxt.js", "Svelte", "SvelteKit", "Gatsby", "Remix",
    "Astro", "Preact", "Alpine.js", "SolidJS", "LitElement", "Ember.js", "Backbone.js", "jQuery",
    "HTML5", "Semantic HTML", "CSS3", "Sass / SCSS", "LESS", "Tailwind CSS", "Bootstrap 5", "Bulma",
    "Chakra UI", "Material-UI (MUI)", "Ant Design", "Shadcn UI", "Radix UI", "Headless UI", "DaisyUI",
    "Styled Components", "Emotion CSS", "CSS Modules", "PostCSS", "Vanilla Extract", "Tailwind Variants",
    "Webpack", "Vite", "Turbopack", "Rollup.js", "Parcel", "Babel", "ESBuild", "SWC Compiler",
    "Redux", "Redux Toolkit (RTK)", "Zustand", "MobX", "Recoil", "Jotai", "XState", "RxJS",
    "TanStack Query (React Query)", "SWR", "Apollo Client", "Relay Modern", "URQL",
    "WebSockets", "Socket.io", "WebRTC", "Service Workers", "Progressive Web Apps (PWA)", "Web Workers",
    "WebAssembly (WASM)", "Three.js", "Babylon.js", "D3.js", "Chart.js", "Recharts", "ECharts",
    "HTML5 Canvas API", "WebGL", "WebGPU", "DOM Manipulation", "Shadow DOM", "Web Components",
    "Micro-Frontends", "Single-SPA", "Module Federation", "Server-Side Rendering (SSR)",
    "Static Site Generation (SSG)", "Incremental Static Regeneration (ISR)", "Client-Side Rendering (CSR)",
    "Hydration Optimization", "Web Vitals Optimization", "Tree Shaking", "Code Splitting",
    // Backend & API Development
    "Node.js", "Express.js", "NestJS", "Fastify", "Koa.js", "Hapi.js", "AdonisJS", "Sails.js", "Feathers.js",
    "Django", "Django REST Framework", "Flask", "FastAPI", "Tornado", "Celery", "Pyramid", "Sanic",
    "Spring Boot", "Spring Cloud", "Spring Security", "Spring Data JPA", "Hibernate ORM", "Quarkus",
    "Micronaut", "Jakarta EE (Java EE)", "Struts", "Dropwizard", "Play Framework", "Akka HTTP",
    "ASP.NET Core", "ASP.NET MVC", ".NET Web API", "Entity Framework Core", "Dapper ORM", "Blazor",
    "SignalR", "WCF Services", "NancyFX", "Ruby on Rails", "Sinatra", "Hanami", "Laravel", "Symfony",
    "CodeIgniter", "Yii Framework", "CakePHP", "Lumen", "Phalcon", "Gin Web Framework", "Echo Framework",
    "Fiber Framework", "Chi Router", "Actix Web", "Rocket.rs", "Axum", "Tonic gRPC", "Ktor", "Micronaut Kotlin",
    "RESTful API Design", "GraphQL API Development", "Apollo Server", "gRPC Services", "Protocol Buffers (Protobuf)",
    "JSON:API Standard", "OpenAPI / Swagger", "SOAP Web Services", "Webhook Architecture", "Event-Driven Architecture",
    "Microservices Architecture", "Monolithic Architecture", "Modular Monolith", "Serverless Architecture",
    "Domain-Driven Design (DDD)", "Command Query Responsibility Segregation (CQRS)", "Event Sourcing",
    "Message Queues", "Apache Kafka", "RabbitMQ", "Apache Pulsar", "ActiveMQ", "ZeroMQ", "Amazon SQS",
    "Amazon SNS", "Google Cloud Pub/Sub", "Azure Service Bus", "NATS Messaging", "BullMQ",
    // Databases, Caching & Search
    "PostgreSQL", "MySQL", "MariaDB", "Oracle Database", "Microsoft SQL Server", "SQLite", "CockroachDB",
    "Amazon Aurora", "Google Cloud Spanner", "YugabyteDB", "TiDB", "IBM Db2", "Informix", "Sybase",
    "MongoDB", "Cassandra", "Couchbase", "Amazon DynamoDB", "Amazon DocumentDB", "Firebase Realtime Database",
    "Cloud Firestore", "RethinkDB", "RavenDB", "ScyllaDB", "Apache HBase", "MarkLogic",
    "Redis", "Memcached", "Aerospike", "Dragonfly Cache", "KeyDB", "Hazelcast",
    "Elasticsearch", "OpenSearch", "Apache Solr", "Meilisearch", "Typesense", "Algolia",
    "Neo4j", "Amazon Neptune", "ArangoDB", "OrientDB", "GraphDB", "JanusGraph", "TigerGraph",
    "TimescaleDB", "InfluxDB", "QuestDB", "VictoriaMetrics", "ClickHouse",
    "Prisma ORM", "TypeORM", "Sequelize", "Mongoose ODM", "Drizzle ORM", "MikroORM", "Bookshelf.js",
    "SQLAlchemy", "Tortoise ORM", "Peewee", "Django ORM", "jOOQ", "MyBatis", "GORM (Go)", "Diesel (Rust)",
    "Database Sharding", "Database Replication", "Read Replicas", "Database Indexing (B-Tree, GiST, GIN)",
    "Query Optimization", "Connection Pooling", "ACID Transactions", "Distributed Transactions (2PC, Saga)",
    // Mobile Development
    "React Native", "Flutter", "Dart for Mobile", "iOS Development", "Android Development", "SwiftUI",
    "UIKit", "Jetpack Compose", "Android SDK", "Android NDK", "Kotlin Multiplatform (KMP)", "Cordova",
    "Capacitor", "Ionic Framework", "Xamarin", ".NET MAUI", "Expo Tools", "Fastlane Automation",
    "Mobile App Security", "In-App Purchases (IAP)", "Apple Push Notification service (APNs)",
    "Firebase Cloud Messaging (FCM)", "App Store Deployment", "Google Play Console", "Mobile Deep Linking",
    "ProGuard / R8 Obfuscation", "Realm Mobile Database", "SQLite for Mobile",
    // Software Testing & QA Automation
    "Unit Testing", "Integration Testing", "End-to-End (E2E) Testing", "Regression Testing", "Smoke Testing",
    "Sanity Testing", "Performance Testing", "Load Testing", "Stress Testing", "Security Testing",
    "Test-Driven Development (TDD)", "Behavior-Driven Development (BDD)", "Jest", "Vitest", "Mocha",
    "Chai Assertion Library", "Jasmine", "Karma Runner", "Cypress", "Playwright", "Selenium WebDriver",
    "Puppeteer", "Appium", "TestCafe", "WebdriverIO", "JUnit 5", "TestNG", "Mockito", "PyTest",
    "Unittest (Python)", "Robot Framework", "Behave (Python BDD)", "NUnit", "xUnit.net", "PHPUnit",
    "RSpec", "Cucumber (BDD)", "Postman API Testing", "Newman CLI", "Insomnia REST Client", "K6 Load Testing",
    "Apache JMeter", "Gatling", "Locust.io", "SonarQube", "ESLint", "Prettier", "Code Coverage (Istanbul/JaCoCo)",
    // System Architecture, Security & Enterprise
    "Object-Oriented Programming (OOP)", "Functional Programming (FP)", "Gang of Four Design Patterns",
    "SOLID Principles", "DRY Principle", "KISS Principle", "YAGNI Principle", "Data Structures & Algorithms",
    "Dynamic Programming", "Graph Algorithms", "Time & Space Complexity Analysis", "High Availability Design",
    "Fault Tolerant Systems", "Load Balancing Algorithms", "Reverse Proxy Setup", "API Gateway Configuration",
    "Rate Limiting / Throttling", "Distributed Caching Strategies", "CAP Theorem Application",
    "Distributed Locking (Redlock)", "Consensus Protocols (Raft, Paxos)", "Circuit Breaker Pattern (Resilience4j)",
    "OAuth 2.0 Authorization", "OpenID Connect (OIDC)", "JWT Authentication", "SAML 2.0 Federation",
    "Single Sign-On (SSO)", "Role-Based Access Control (RBAC)", "Attribute-Based Access Control (ABAC)",
    "Zero Trust Architecture", "HTTPS / TLS 1.3 / SSL", "CORS Security Policy", "CSRF Mitigation",
    "XSS Sanitization", "SQL Injection Mitigation", "Content Security Policy (CSP)", "PKI Infrastructure",
    "Bcrypt / Argon2 Password Hashing", "AES-256 Encryption", "RSA Asymmetric Encryption", "HMAC Signatures",
    "TCP/IP Protocols", "UDP Sockets", "DNS Configuration", "HTTP/2 & HTTP/3 Protocols", "Cloudflare CDN",
    "AWS CloudFront CDN", "Akamai CDN", "Web Application Firewall (WAF)", "DDoS Protection",
    // Embedded, Game, Blockchain & Tools
    "Embedded C/C++", "RTOS (FreeRTOS, Zephyr)", "Microcontroller Programming", "Arduino Architecture",
    "Raspberry Pi GPIO", "ESP32 / ESP8266", "STM32 Microcontrollers", "Firmware Flashing", "CAN Bus Protocol",
    "I2C Protocol", "SPI Protocol", "UART Serial Communication", "BLE (Bluetooth Low Energy)", "Zigbee Protocol",
    "Unity Engine", "Unreal Engine 5", "Godot Engine", "C# for Unity", "C++ for Unreal", "Game Physics Engines",
    "Shader Programming (HLSL/GLSL)", "Blender Integration", "Game AI Programming", "Multiplayer Netcode",
    "Smart Contract Development", "Solidity Security Auditing", "EVM Internals", "Web3.js", "Ethers.js",
    "Hardhat Framework", "Foundry Ethereum", "Truffle Suite", "IPFS Distributed Storage", "ZK-Rollups",
    "Git Version Control", "GitHub Workflows", "GitLab", "Bitbucket", "Git Flow Branching", "Trunk-Based Development",
    "Jira Issue Tracking", "Confluence Documentation", "Linear App", "Asana for Engineering", "Technical Writing",
    "Architecture Decision Records (ADR)", "C4 Model Diagrams", "UML Modeling", "Refactoring Legacy Systems"
  ],

  "Data Science & Analytics": [
    // Mathematics & Statistics Foundations
    "Linear Algebra", "Matrix Decompositions (SVD, Cholesky)", "Multivariate Calculus", "Gradient Descent Optimization",
    "Probability Distributions", "Bayesian Inference", "Markov Chain Monte Carlo (MCMC)", "Descriptive Statistics",
    "Inferential Statistics", "Null Hypothesis Significance Testing", "p-value Interpretation", "Z-Test & T-Test",
    "Chi-Square Test", "ANOVA (Analysis of Variance)", "MANOVA", "Mann-Whitney U Test", "Wilcoxon Signed-Rank Test",
    "Confidence Intervals", "Statistical Power & Sample Size Determination", "Bootstrapping & Resampling",
    "Ordinary Least Squares (OLS)", "Polynomial Regression", "Ridge Regression (L2)", "Lasso Regression (L1)",
    "ElasticNet Regularization", "Logistic Regression Analysis", "Generalized Linear Models (GLM)",
    "Survival Analysis (Kaplan-Meier, Cox Proportional Hazards)", "Time Series Forecasting",
    "ARIMA / SARIMA Models", "Exponential Smoothing (Holt-Winters)", "Prophet (Meta)", "GARCH Modeling",
    "Stationarity & Unit Root Testing (ADF Test)", "Autocorrelation & Partial Autocorrelation (ACF/PACF)",
    // Python & R Data Science Libraries
    "Python for Analytics", "R for Data Science", "NumPy", "Pandas DataFrames", "Polars Library", "Dask Distributed",
    "SciPy Scientific Library", "Statsmodels", "Numba JIT", "Cython for Speed", "Jupyter Notebooks",
    "JupyterLab", "Google Colab Pro", "RStudio Environment", "Tidyverse (R)", "dplyr (R)", "tidyr (R)",
    "data.table (R)", "lubridate", "stringr", "purrr", "BioPython", "GeoPandas for Spatial Data",
    "Shapely", "PySal", "Rasterio", "NetworkX (Graph Analysis)", "igraph",
    // Data Cleaning, Wrangling & Preprocessing
    "Data Wrangling", "Data Imputation Techniques (KNN, MICE)", "Outlier Detection (Z-score, IQR, Isolation Forest)",
    "Feature Engineering", "Categorical Encoding (One-Hot, Target, Binary)", "Feature Scaling (StandardScaler, MinMaxScaler)",
    "Feature Selection (RFE, LASSO, Mutual Information)", "Variance Inflation Factor (VIF)", "Principal Component Analysis (PCA)",
    "t-Distributed Stochastic Neighbor Embedding (t-SNE)", "Uniform Manifold Approximation and Projection (UMAP)",
    "Factor Analysis", "Independent Component Analysis (ICA)", "Data Standardization & Normalization",
    "Box-Cox Transformation", "Handling Class Imbalance (SMOTE, ADASYN, Random Undersampling)",
    // Data Visualization & Business Intelligence (BI)
    "Exploratory Data Analysis (EDA)", "Data Storytelling", "Matplotlib Visualization", "Seaborn Statistical Plots",
    "Plotly Interactive Graphs", "Bokeh Dashboards", "Altair Declarative Viz", "ggplot2 (R)", "Folium Map Visuals",
    "Tableau Desktop", "Tableau Server Management", "Tableau Prep Builder", "Calculated Fields in Tableau",
    "Tableau LOD Expressions", "Power BI Desktop", "Power BI Service", "DAX (Data Analysis Expressions)",
    "Power Query M Formula", "Data Modeling in Power BI", "Row-Level Security (RLS) in Power BI",
    "Looker (Google Cloud)", "LookML Development", "Looker Studio (Google Data Studio)", "Metabase BI",
    "Apache Superset", "Qlik Sense", "QlikView Development", "MicroStrategy", "ThoughtSpot Analytics",
    "Executive KPI Dashboards", "Interactive Heatmaps", "Choropleth Maps", "Funnel Visualizations",
    // Machine Learning Algorithms
    "Supervised Machine Learning", "Unsupervised Machine Learning", "Semi-Supervised Learning",
    "Reinforcement Learning (RL)", "Q-Learning", "Deep Q-Networks (DQN)", "Policy Gradient Methods",
    "Scikit-Learn Framework", "Decision Tree Classifiers/Regressors", "Random Forest Ensembles",
    "Extra Trees", "Gradient Boosting Machines (GBM)", "XGBoost Library", "LightGBM Library",
    "CatBoost Library", "AdaBoost Classifier", "Support Vector Machines (SVM)", "Kernel Tricks in SVM",
    "K-Nearest Neighbors (KNN)", "Gaussian Naive Bayes", "Multinomial Naive Bayes", "K-Means Clustering",
    "K-Medoids Clustering", "Agglomerative Hierarchical Clustering", "DBSCAN Density Clustering",
    "HDBSCAN", "Mean Shift Clustering", "Gaussian Mixture Models (GMM)", "Association Rule Mining (Apriori, FP-Growth)",
    "Hyperparameter Tuning", "Grid Search CV", "Randomized Search CV", "Bayesian Optimization (Hyperopt, Optuna)",
    "K-Fold Cross-Validation", "Stratified K-Fold", "Confusion Matrix Evaluation", "Precision & Recall Optimization",
    "F1-Score / Macro & Micro F1", "ROC-AUC Metric", "PR-AUC Curves", "Log-Loss Metric", "Mean Squared Error (MSE)",
    "Root Mean Squared Error (RMSE)", "Mean Absolute Error (MAE)", "R-Squared Metric",
    // Deep Learning & Neural Networks
    "Deep Learning Architecture", "Artificial Neural Networks (ANN)", "Perceptrons & Multi-Layer Perceptrons (MLP)",
    "Backpropagation Algorithm", "Activation Functions (ReLU, GELU, Sigmoid, Tanh, Swish)",
    "Optimization Algorithms (Adam, AdamW, RMSprop, SGD)", "Dropout Regularization", "Batch Normalization",
    "Layer Normalization", "Weight Initialization (He, Xavier/Glorot)", "Convolutional Neural Networks (CNN)",
    "Residual Networks (ResNet)", "VGG Architectures", "Inception Modules", "EfficientNet", "DenseNet",
    "Recurrent Neural Networks (RNN)", "Long Short-Term Memory (LSTM)", "Gated Recurrent Unit (GRU)",
    "Bidirectional RNNs", "Sequence-to-Sequence Models (Seq2Seq)", "Attention Mechanism (Bahdanau, Luong)",
    "Self-Attention & Multi-Head Attention", "Transformer Networks", "Autoencoders", "Variational Autoencoders (VAE)",
    "Generative Adversarial Networks (GAN)", "DCGAN", "CycleGAN", "Diffusion Models (DDPM)",
    "PyTorch Framework", "PyTorch Lightning", "TorchScript", "TensorFlow 2.x", "Keras API", "JAX Framework",
    "Flax Library", "Hugging Face Ecosystem", "Transformers Library", "Datasets Library", "Evaluate Library",
    "ONNX Runtime", "NVIDIA TensorRT", "CUDA C++ Programming", "GPU Cluster Distributed Training (DDP, FSDP)",
    "DeepSpeed Optimization", "Megatron-LM",
    // Natural Language Processing (NLP) & GenAI
    "Natural Language Processing (NLP)", "Text Tokenization (BPE, WordPiece, SentencePiece)",
    "Stemming (Porter, Snowball)", "Lemmatization (WordNet)", "Stop Words Removal", "N-Gram Language Models",
    "TF-IDF Vectorization", "Word2Vec (Skip-Gram, CBOW)", "GloVe Word Embeddings", "FastText (Facebook)",
    "BERT Language Model", "RoBERTa", "DistilBERT", "DeBERTa", "XLNet", "Electra", "T5 (Text-to-Text Transfer)",
    "BART Architecture", "GPT-3 / GPT-4 Architecture", "LLaMA 2 / LLaMA 3 Architecture", "Mistral & Mixtral Models",
    "Large Language Models (LLMs)", "Generative AI Application Development", "Prompt Engineering Techniques",
    "Few-Shot & Chain-of-Thought (CoT) Prompting", "Tree of Thoughts (ToT)", "LLM Fine-Tuning",
    "Low-Rank Adaptation (LoRA)", "Quantized LoRA (QLoRA)", "Prefix Tuning / P-Tuning", "Parameter-Efficient Fine-Tuning (PEFT)",
    "RLHF (Reinforcement Learning from Human Feedback)", "DPO (Direct Preference Optimization)",
    "Retrieval-Augmented Generation (RAG)", "Advanced RAG (Hybrid Search, Re-ranking)", "LangChain Framework",
    "LlamaIndex Framework", "Semantic Kernel", "Vector Databases", "Pinecone Vector DB", "Milvus Database",
    "ChromaDB", "Weaviate Vector Search", "Qdrant Vector DB", "FAISS (Facebook AI Similarity Search)",
    "Sentence Transformers", "Text Embeddings (OpenAI, Cohere)", "Cross-Encoders for Reranking",
    "Named Entity Recognition (NER)", "Part-of-Speech (POS) Tagging", "Dependency Parsing", "Sentiment Analysis",
    "Text Summarization (Extractive & Abstractive)", "Topic Modeling (LDA, BERTopic)", "Question Answering Systems",
    "Speech Recognition (Whisper AI)", "Text-to-Speech (TTS)", "Conversational AI Agents",
    // Computer Vision
    "Computer Vision (CV)", "OpenCV Library", "Digital Image Processing", "Image Filtering & Kernels",
    "Edge Detection (Canny, Sobel)", "Hough Transform", "Morphological Operations", "Image Segmentation (Semantic & Instance)",
    "U-Net Architecture", "Mask R-CNN", "Segment Anything Model (SAM)", "Object Detection",
    "YOLO Series (YOLOv5, YOLOv8, YOLOv9)", "SSD (Single Shot MultiBox Detector)", "Faster R-CNN",
    "Face Detection & Recognition (FaceNet, InsightFace)", "Optical Character Recognition (OCR)",
    "Tesseract OCR", "EasyOCR", "PaddleOCR", "Pose Estimation (MediaPipe, OpenPose)",
    "Image Generation & Inpainting (Stable Diffusion, ControlNet)", "Video Action Recognition",
    // Big Data Analytics & Distributed Computing
    "Big Data Architecture", "Apache Spark Engine", "PySpark Development", "Spark SQL Queries",
    "Spark Structured Streaming", "Spark MLlib", "Apache Hadoop Framework", "Hadoop Distributed File System (HDFS)",
    "Apache Hive Data Warehouse", "Apache HBase NoSQL", "Apache Flink Stream Processing", "Apache Beam",
    "Presto / Trino Distributed SQL", "Delta Lake Architecture", "Apache Iceberg Tables", "Apache Hudi",
    "Snowflake Cloud Data Warehouse", "Google BigQuery", "Amazon Redshift", "Databricks Unified Analytics Platform",
    "dbt (data build tool)", "Dimensional Modeling (Kimball)", "Star Schema & Snowflake Schema Design",
    "Data Lakehouse Concept", "ETL & ELT Pipeline Engineering",
    // MLOps & Production Engineering
    "MLOps Best Practices", "MLflow Experiment Tracking", "Weights & Biases (W&B)", "Neptune.ai",
    "DVC (Data Version Control)", "Kubeflow Pipelines", "Seldon Core for K8s", "BentoML Serving",
    "TorchServe Deployment", "Triton Inference Server", "FastAPI for Model Serving", "Streamlit App Development",
    "Gradio Interfaces", "Docker for ML Environments", "Model Drift Detection (Data & Concept Drift)",
    "Evidently AI Monitoring", "Feature Stores (Feast, Tecton)", "Model Explainability (SHAP Values, LIME)",
    "Model Quantization (INT8, FP4, GGUF, AWQ)", "Model Pruning & Distillation",
    // Domain & Business Analytics
    "Customer Churn Modeling", "Customer Lifetime Value (CLV/LTV)", "Customer Segmentation (RFM Analysis)",
    "Cohort Retention Analysis", "Conversion Rate Analysis", "Market Basket Analysis",
    "Recommendation Engines (Collaborative & Content-Based)", "Fraud Detection Algorithms",
    "Credit Risk Scoring (FICO, Scorecards)", "Algorithmic Trading Strategies", "Product Analytics (Mixpanel, Amplitude)",
    "A/B Test Design & Sample Size Calculation", "Marketing Mix Modeling (MMM)", "Multi-Touch Attribution (MTA)"
  ],

  "Product Management": [
    // Product Strategy, Vision & Market Analysis
    "Product Strategy Formulation", "Product Vision Development", "Product Lifecycle Management (PLM)",
    "Go-To-Market (GTM) Strategy", "Value Proposition Design", "Business Model Canvas (BMC)",
    "Lean Canvas Modeling", "SWOT Analysis for Products", "PESTLE Analysis", "Porter's Five Forces",
    "Competitive Intelligence", "Market Sizing (TAM, SAM, SOM)", "Product-Market Fit (PMF) Validation",
    "Target Addressable Market Estimation", "Disruptive Innovation Strategies", "Blue Ocean Strategy",
    "Pricing & Packaging Strategy", "SaaS Pricing Models", "Freemium Conversion Strategies",
    "Monetization Strategy", "Platform Ecosystem Strategy", "Two-Sided Marketplaces Dynamics",
    "Strategic Positioning & Messaging", "Defensibility & Moat Building", "Product Portfolio Management",
    // Discovery, Research & Customer Empathy
    "Customer Discovery Process", "Qualitative User Interviews", "Quantitative Survey Design",
    "Voice of Customer (VoC) Programs", "User Persona Development", "Jobs-to-be-Done (JTBD) Framework",
    "Customer Journey Mapping", "User Story Mapping", "Empathy Mapping", "Problem Space vs. Solution Space",
    "Customer Pain Point Synthesis", "Usability Testing Insights", "Focus Group Moderation",
    "Diary Study Facilitation", "Contextual Inquiry Research", "Customer Advisory Boards (CAB)",
    "Beta Customer Co-Development", "Customer Feedback Loop Design", "NPS Feedback Analysis",
    // Requirements Definition & Technical Execution
    "Product Requirements Document (PRD)", "Functional Specifications", "Business Requirements Document (BRD)",
    "User Story Writing", "Acceptance Criteria Definition", "Definition of Ready (DoR)",
    "Definition of Done (DoD)", "Product Backlog Management", "Backlog Grooming & Refinement",
    "Feature Prioritization Frameworks", "RICE Prioritization (Reach, Impact, Confidence, Effort)",
    "MoSCoW Method", "Kano Model Analysis", "Value vs. Complexity Matrix", "Cost of Delay (WSJF)",
    "Story Point Estimation", "Planning Poker Facilitation", "Sprint Planning Meetings",
    "Daily Standup Facilitation", "Sprint Review & Demo", "Sprint Retrospective Moderation",
    "Agile Methodology", "Scrum Framework", "Kanban Method", "Scaled Agile Framework (SAFe)",
    "Scrumban Hybrid", "Extreme Programming (XP) Practices", "Minimum Viable Product (MVP) Definition",
    "Minimum Lovable Product (MLP)", "Proof of Concept (PoC) Validation", "Feature Flagging (LaunchDarkly, Split)",
    "Progressive Rollout Strategies", "Release Management Workflows", "Bug Triage & Prioritization",
    // Metrics, KPIs & Analytics
    "Product Analytics Interpretation", "North Star Metric Identification", "Key Performance Indicators (KPIs)",
    "OKRs (Objectives and Key Results)", "A/B Testing Experimentation", "Multivariate Testing (MVT)",
    "Hypothesis Formulation", "Statistical Significance in Experiments", "Sample Size Calculation",
    "Cohort Retention Analysis", "Churn Rate Reduction", "Net Promoter Score (NPS) Strategy",
    "Customer Satisfaction Score (CSAT)", "Customer Effort Score (CES)", "Daily Active Users (DAU)",
    "Monthly Active Users (MAU)", "DAU/MAU Stickiness Ratio", "Session Length & Frequency",
    "Feature Adoption Rate", "Time-to-Value (TTV) Optimization", "Activation Funnel Optimization",
    "Drop-Off Point Identification", "Amplitude Analytics", "Mixpanel Analytics", "Google Analytics 4 (GA4)",
    "Heap Analytics", "Pendo Product Cloud", "FullStory Session Replay", "Hotjar Heatmaps & Recordings",
    "Crazy Egg", "Optimizely Platform", "VWO (Visual Website Optimizer)", "Looker for Product Metrics",
    // Growth & Product-Led Growth (PLG)
    "Product-Led Growth (PLG)", "Self-Serve User Onboarding", "Frictionless Sign-Up Flows",
    "Aha! Moment Optimization", "Viral Coefficient (K-Factor) Engineering", "Referral Loops & Programs",
    "Expansion Revenue Workflows", "In-App Upselling & Cross-Selling", "Product-Led Sales (PLS)",
    "Product Qualified Leads (PQL)", "Usage-Based Pricing Triggers", "Growth Loops vs. Traditional Funnels",
    "Flywheel Business Model", "Customer Acquisition Cost (CAC)", "LTV:CAC Ratio Optimization",
    "Payback Period Analysis", "Retention Curve Flattening", "Growth Experiment Sprints",
    // Specialized Domain Product Management
    "Technical Product Management (TPM)", "API Product Management", "Developer Experience (DX) Design",
    "SDK & Developer Portal Management", "B2B SaaS Product Management", "Enterprise Software Strategy",
    "B2C Consumer Mobile Apps", "FinTech Product Regulations (PCI, KYC, AML)", "HealthTech HIPAA Compliance",
    "EdTech Engagement Strategies", "E-Commerce Cart & Checkout Optimization", "AI & Machine Learning Productization",
    "Data Platform Product Management", "Cybersecurity Product Management", "Hardware/IoT Product Management",
    // Stakeholder Management, Leadership & Tools
    "Cross-Functional Team Leadership", "Executive Stakeholder Communication", "Engineering-Product Alignment",
    "Design-Product Collaboration", "Sales Enablement Alignment", "Customer Success Collaboration",
    "Influence Without Authority", "Negotiation & Trade-Off Management", "Conflict Resolution",
    "Change Management (ADKAR)", "Vendor Evaluation & RFPs", "Product Roadmapping Tools",
    "Jira Software Administration", "Confluence Documentation", "Productboard Management",
    "Aha! Roadmaps", "Linear App for PMs", "Notion Workspace Architecture", "Miro Collaborative Whiteboards",
    "Mural Whiteboards", "Lucidchart Process Flowcharts", "Figma for Product Managers", "Loom Video Communication"
  ],

  "UI/UX & Design": [
    // User Experience (UX) Research & Strategy
    "User Experience (UX) Strategy", "User Research Methodologies", "Qualitative User Research",
    "Quantitative User Research", "Generative User Research", "Evaluative Research",
    "User Interview Facilitation", "Semi-Structured Interviews", "Contextual Inquiry",
    "Ethnographic Field Studies", "Diary Studies Management", "Usability Testing (Moderated & Unmoderated)",
    "Remote Usability Testing", "Think-Aloud Protocol", "Card Sorting (Open & Closed)",
    "Tree Testing for Information Architecture", "Heuristic Evaluation (Nielsen's 10 Heuristics)",
    "Cognitive Walkthrough", "Expert Design Reviews", "Competitive UX Benchmarking",
    "User Journey Mapping", "Customer Experience (CX) Architecture", "Service Blueprinting",
    "Information Architecture (IA)", "Site Mapping & Hierarchy", "Task Flow Diagrams",
    "User Flow Diagrams", "Mental Models Construction", "Affinity Diagramming Synthesis",
    "User Persona Creation", "Empathy Mapping Workshops", "Scenario & Storyboarding",
    // User Interface (UI) Design & Visual Craft
    "User Interface (UI) Design", "Visual Hierarchy & Layout", "Design Systems Architecture",
    "Component Libraries Creation", "Design Tokens Management", "Atomic Design Methodology",
    "Wireframing (Low-Fidelity & Mid-Fidelity)", "High-Fidelity UI Mockups", "Rapid Prototyping",
    "Interactive Prototyping", "Micro-Interactions Design", "UI Style Guide Creation",
    "Typography in Digital UI", "Type Scale & Vertical Rhythm", "Font Pairing & Legibility",
    "Grid Systems (8pt Grid, 12-Column Responsive)", "Negative Space & White Space Utilization",
    "Color Theory & Harmonies", "Accessible Color Palette Generation", "Contrast Ratios (WCAG AA/AAA)",
    "Iconography Design & SVG Optimization", "Vector Illustration Creation", "Asset Exporting & Management",
    "Responsive Web Design", "Mobile-First Design Philosophy", "Desktop & Tablet Adaptive Layouts",
    "Dark Mode & Light Mode Theming", "Skeuomorphism vs. Flat Design vs. Neumorphism", "Glassmorphism Aesthetics",
    // Design Software & Prototyping Tools
    "Figma Mastery", "Figma Auto Layout 5.0", "Figma Component Variants & Properties", "Figma Design Tokens",
    "Figma Interactive Components", "Figma Variables & Modes", "Figma Plugins Creation", "FigJam Collaboration",
    "Adobe XD", "Sketch App", "InVision Studio", "Axure RP Advanced Logic", "Balsamiq Mockups",
    "Framer Web Builder", "Webflow Visual Development", "Origami Studio (Meta)", "Principle for Mac",
    "ProtoPie (Sensors, Logic, Formulas)", "Zeplin Handoff", "Storybook Integration for Designers",
    "Adobe Creative Cloud Suite", "Adobe Photoshop (Photo Manipulation & Mockups)",
    "Adobe Illustrator (Vector Graphics & Logos)", "Adobe After Effects (Motion UI)",
    "Adobe InDesign", "Canva for Pro Graphics",
    // Motion Design & Emerging Formats
    "Interaction Design (IxD)", "Motion Design Principles (Disney's 12 Principles in UI)",
    "UI Animation & Micro-Interactions", "Lottie Animations (Bodymovin)", "Rive Interactive Animations",
    "CSS Animations & Keyframes Literacy", "Transition Timing & Easing Curves (Cubic-Bezier)",
    "3D Web Design", "Spline 3D Tool", "Blender for UI Assets", "Augmented Reality (AR) UI Design",
    "Virtual Reality (VR) Spatial UI", "Apple VisionOS Human Interface Guidelines", "Voice User Interface (VUI) Design",
    "Audio & Haptic Feedback Design", "Chatbot & Conversational UI Design", "Game UI/HUD Design",
    // Accessibility (a11y) & Inclusive Design
    "Digital Accessibility (a11y)", "WCAG 2.1 & 2.2 Standards Compliance", "Section 508 Accessibility Compliance",
    "Color Contrast Analyzer Tools", "Screen Reader Navigation (NVDA, VoiceOver, JAWS)",
    "Keyboard-Only Navigation Design", "Focus Indicators & Skip Links", "Inclusive Design Frameworks",
    "Universal Design Principles", "Accessible Form Validation & Error States", "Alternative Text (Alt Text) Guidelines",
    "Ethical UI & Anti-Dark Patterns", "Neurodiverse UX Considerations",
    // Design Collaboration, Workshops & Developer Handoff
    "Developer Handoff Workflows", "Design System Documentation (Zeroheight, Supernova)",
    "HTML5 & CSS3 Literacy for Designers", "Flexbox & CSS Grid Mental Models", "Design QA & Pixel-Perfect Auditing",
    "Visual Regression Review", "Redlining & Dimension Specs", "Design Sprint Facilitation (GV Sprint)",
    "Ideation & Brainstorming Workshops", "Crazy Eights Ideation", "Design Critique Moderation",
    "Creative Direction", "Brand Identity & Guidelines Integration", "Logo Design & Vectorization"
  ],

  "DevOps & Infrastructure": [
    // Cloud Platforms (AWS, Azure, GCP & Multi-Cloud)
    "Amazon Web Services (AWS)", "AWS EC2 (Elastic Compute Cloud)", "AWS S3 (Simple Storage Service)",
    "AWS Lambda Serverless", "AWS ECS (Elastic Container Service)", "AWS EKS (Elastic Kubernetes Service)",
    "AWS Fargate", "AWS RDS (Relational Database Service)", "AWS DynamoDB Management",
    "AWS CloudFront CDN", "AWS Route 53 DNS", "AWS IAM (Identity and Access Management)",
    "AWS VPC (Virtual Private Cloud)", "AWS CloudWatch Monitoring", "AWS CloudTrail Auditing",
    "AWS CloudFormation Templates", "AWS Elastic Beanstalk", "AWS KMS (Key Management Service)",
    "AWS Secrets Manager", "AWS Systems Manager (SSM)", "AWS Step Functions",
    "Microsoft Azure Cloud", "Azure Virtual Machines (VMs)", "Azure App Service", "Azure Kubernetes Service (AKS)",
    "Azure Blob Storage", "Azure SQL Database", "Azure Cosmos DB", "Azure DevOps Services",
    "Azure Resource Manager (ARM) Templates", "Azure Bicep", "Azure Virtual Network (VNet)",
    "Azure Active Directory (Azure AD / Entra ID)", "Azure Key Vault", "Azure Monitor & Log Analytics",
    "Google Cloud Platform (GCP)", "Google Compute Engine (GCE)", "Google Kubernetes Engine (GKE)",
    "Google Cloud Run", "Google Cloud Functions", "Google Cloud Storage (GCS)", "Google Cloud SQL",
    "Google Cloud Spanner", "Google Cloud Pub/Sub", "Google Cloud IAM", "Google Cloud VPC",
    "Google Cloud Operations Suite (Stackdriver)", "DigitalOcean Droplets & Kubernetes",
    "Linode / Akamai Cloud", "Cloudflare Workers & Pages", "Cloudflare Zero Trust & DNS",
    "Vercel Enterprise Infrastructure", "Heroku Platform Administration", "Hybrid Cloud Architecture",
    // Containers & Container Orchestration
    "Docker Engine", "Dockerfile Best Practices", "Multi-Stage Docker Builds", "Docker Compose Orchestration",
    "Docker Swarm", "Podman Container Tool", "Containerd Runtime", "CRI-O Runtime", "Buildah & Skopeo",
    "Kubernetes (K8s) Architecture", "Kubernetes Pods & Deployments", "Kubernetes ReplicaSets",
    "Kubernetes StatefulSets", "Kubernetes DaemonSets", "Kubernetes Jobs & CronJobs",
    "Kubernetes Services (ClusterIP, NodePort, LoadBalancer)", "Kubernetes Ingress Controllers (Nginx, Traefik, HAProxy)",
    "Kubernetes ConfigMaps & Secrets", "Kubernetes Persistent Volumes (PV) & PVCs", "Kubernetes StorageClasses",
    "Kubernetes Horizontal Pod Autoscaler (HPA)", "Vertical Pod Autoscaler (VPA)", "Kubernetes Cluster Autoscaler",
    "Kubernetes RBAC Policies", "Kubernetes NetworkPolicies", "Helm Package Manager", "Helm Charts Development",
    "Kustomize Configuration Tool", "K9s CLI Dashboard", "Minikube Local K8s", "Kind (Kubernetes in Docker)",
    "k3s Lightweight K8s", "HashiCorp Nomad", "Red Hat OpenShift Platform",
    "Container Security Scanning (Trivy, Clair, Anchore, Snyk Container)", "Container Registry Management (Harbor, AWS ECR, ACR, GCR)",
    // Infrastructure as Code (IaC) & Automation
    "Infrastructure as Code (IaC)", "HashiCorp Terraform", "Terraform HCL Syntax", "Terraform State Management (Remote State, Locking)",
    "Terraform Modules Architecture", "Terraform Workspaces", "Terragrunt Orchestration", "Pulumi (TypeScript/Python IaC)",
    "Ansible Automation Engine", "Ansible Playbooks Development", "Ansible Roles & Galaxy",
    "Ansible Inventory Management", "Red Hat Ansible Tower / AWX", "Chef Configuration Management",
    "Puppet Automation", "SaltStack (Salt)", "HashiCorp Packer (Golden Images)", "Vagrant Development Environments",
    "Cloud-Init Provisioning", "Immutable Infrastructure Pattern", "Drift Detection & Reconciliation",
    // CI/CD Pipelines & GitOps
    "Continuous Integration (CI)", "Continuous Delivery & Deployment (CD)", "CI/CD Pipeline Architecture",
    "Jenkins Automation Server", "Jenkins Declarative & Scripted Pipelines", "Jenkins Shared Libraries",
    "GitHub Actions Workflows", "GitHub Custom Composite Actions", "GitLab CI/CD Pipelines",
    "GitLab Runner Administration", "CircleCI Pipelines", "Travis CI", "Bitbucket Pipelines",
    "TeamCity CI Server", "Atlassian Bamboo", "Argo CD GitOps", "Flux CD GitOps", "GitOps Operating Model",
    "Spinnaker Multi-Cloud CD", "Tekton Pipelines", "Drone CI", "Blue-Green Deployment Strategies",
    "Canary Deployment Strategies", "Rolling Updates & Zero-Downtime Releases", "Feature Toggling in CI/CD",
    "Automated Rollback Systems", "Artifact Repository Management (JFrog Artifactory, Sonatype Nexus)",
    // Monitoring, Observability & Site Reliability (SRE)
    "Observability Practices", "Site Reliability Engineering (SRE)", "Prometheus Monitoring System",
    "PromQL Query Language", "Prometheus Exporters", "Grafana Visualization Dashboards", "Grafana Alerting",
    "Alertmanager Configuration", "Datadog Cloud Monitoring", "Datadog APM & Synthetics", "New Relic Full Stack Observability",
    "Dynatrace AI Monitoring", "AppDynamics APM", "Splunk Enterprise Logging", "Splunk SPL Queries",
    "ELK Stack (Elasticsearch, Logstash, Kibana)", "EFK Stack (Elasticsearch, Fluentd, Kibana)",
    "Grafana Loki for Log Aggregation", "Grafana Tempo for Distributed Tracing", "OpenTelemetry (OTel) Standards",
    "Jaeger Distributed Tracing", "Zipkin Tracing", "Synthetic Monitoring & Heartbeats", "Real User Monitoring (RUM)",
    "Uptime Robot & Status Pages", "PagerDuty Incident Response", "OpsGenie On-Call Management",
    "VictorOps / Splunk On-Call", "Incident Management Protocols", "Blameless Post-Mortem Facilitation",
    "Root Cause Analysis (RCA)", "Service Level Objectives (SLO)", "Service Level Indicators (SLI)",
    "Service Level Agreements (SLA)", "Error Budget Policies", "Capacity Planning & Forecasting",
    // Networking, Security & Service Mesh
    "Linux System Administration (RHEL, CentOS, Ubuntu, Debian, Alpine)", "Linux Performance Tuning (sysctl)",
    "Systemd Service Management", "Shell Scripting (Bash, Zsh)", "Python Scripting for DevOps",
    "SSH Key Infrastructure & Bastion Hosts", "Computer Networking Fundamentals (OSI Model)",
    "TCP/IP Stack Configuration", "Subnetting, CIDR & VLANs", "Virtual Private Cloud (VPC) Peering",
    "AWS Direct Connect / Azure ExpressRoute", "VPN Setup (OpenVPN, WireGuard, IPsec)",
    "NAT Gateways & Route Tables", "BGP Routing Protocol", "DNS Management (BIND, Unbound)",
    "Nginx Reverse Proxy & Load Balancer", "HAProxy High Performance Proxy", "Apache HTTP Server",
    "Envoy Proxy Architecture", "Service Mesh Implementations", "Istio Service Mesh", "Linkerd Lightweight Mesh",
    "HashiCorp Consul Service Discovery", "Mutual TLS (mTLS) Encryption", "Let's Encrypt & Certbot SSL Automation",
    "HashiCorp Vault Secrets Management", "Cloud Secrets Stores (AWS Secrets Manager, Azure Key Vault)",
    "Cybersecurity Frameworks (CIS Benchmarks, NIST)", "SOC 2 Type II Infrastructure Compliance",
    "PCI-DSS Server Hardening", "HIPAA Cloud Compliance", "Disaster Recovery (DR) Orchestration",
    "Active-Active Multi-Region High Availability", "Backup & Restore Automation (Velero for K8s)",
    "Chaos Engineering Principles", "Chaos Mesh", "Gremlin Chaos Engineering", "Load Testing Infrastructure"
  ],

  "Marketing & Content": [
    // Marketing Strategy, Brand & Planning
    "Marketing Strategy Formulation", "Growth Marketing Strategy", "Performance Marketing Planning",
    "Omnichannel Marketing Strategy", "Brand Strategy Development", "Brand Identity & Architecture",
    "Brand Positioning & Messaging", "Competitive Intelligence & Benchmarking", "Customer Acquisition Strategy",
    "Customer Retention & Loyalty Marketing", "Marketing Budget Allocation & Forecasting", "Marketing Mix Modeling (MMM)",
    "Customer Journey Mapping", "Buyer Persona Research & Construction", "Go-to-Market (GTM) Campaign Planning",
    "Product Launch Marketing", "Demand Generation Strategy", "Lead Nurturing Frameworks",
    // Search Engine Optimization (SEO)
    "Search Engine Optimization (SEO)", "On-Page SEO Optimization", "Off-Page SEO & Link Acquisition",
    "Technical SEO Auditing", "Keyword Research & Clustering", "Search Intent Classification",
    "Content Gap Analysis", "Core Web Vitals Optimization for SEO", "Schema.org Structured Data Markup",
    "XML Sitemaps & Robots.txt Directives", "Canonical URL Management", "Internal Linking Architecture",
    "Backlink Outreach & Digital PR", "Local SEO & Google Business Profile Optimization",
    "International SEO (Hreflang Implementation)", "E-Commerce SEO (Shopify, WooCommerce, Magento)",
    "YouTube SEO Optimization", "App Store Optimization (ASO - iOS App Store & Google Play)",
    "Ahrefs SEO Suite", "Semrush Marketing Toolkit", "Moz Pro Tools", "Screaming Frog SEO Spider",
    "Google Search Console Audits", "Google Trends Analysis", "SurferSEO Content Optimization", "Clearscope",
    // Search Engine Marketing (SEM) & Paid Advertising
    "Search Engine Marketing (SEM)", "Pay-Per-Click Advertising (PPC)", "Google Ads Management",
    "Google Search Ads Campaigns", "Google Display Network (GDN)", "Google Shopping Ads & Merchant Center",
    "Performance Max (PMax) Campaigns", "YouTube Video Advertising", "Microsoft Advertising (Bing Ads)",
    "Meta Ads Manager (Facebook & Instagram Ads)", "Meta Custom Audiences & Lookalike Audiences",
    "Retargeting & Remarketing Strategies", "LinkedIn Campaign Manager (Sponsored Content, InMail)",
    "Twitter / X Advertising", "TikTok Ads Manager", "Pinterest Business Advertising",
    "Reddit Ads Platform", "Amazon PPC & Sponsored Products", "Programmatic Advertising & DSPs",
    "Ad Copywriting & Creative Testing", "Creative A/B Testing & Iteration", "Google Ads Quality Score Optimization",
    "Bid Strategies (Target CPA, Target ROAS, Maximize Conversions)", "Negative Keyword Sculpting",
    // Content Strategy, Copywriting & Storytelling
    "Content Marketing Strategy", "Content Lifecycle Management", "Editorial Calendar Planning",
    "Copywriting & Persuasive Writing", "Creative Writing for Brands", "B2B SaaS Copywriting",
    "Direct Response Copywriting", "Long-Form Content Creation", "Technical Blog Writing",
    "White Paper Authoring", "E-Book Production", "Customer Case Study Writing",
    "Thought Leadership Articles (Forbes, LinkedIn)", "Press Release Writing (PR Newswire)",
    "Technical Documentation for Users", "Executive Speechwriting", "Video Scriptwriting & Storyboarding",
    "Podcast Scripting & Production", "Ghostwriting for Founders", "Content Repurposing Strategies",
    "Copyediting & Proofreading", "AP Stylebook Guidelines", "Chicago Manual of Style (CMOS)",
    "Brand Storytelling & Narrative Craft", "UX Writing & Microcopy", "Landing Page Headline Optimization",
    "Call-to-Action (CTA) Optimization", "Grammarly Business & Hemingway Editor",
    // Social Media Marketing (SMM) & Community
    "Social Media Marketing (SMM)", "Organic Social Media Growth", "Social Media Community Management",
    "LinkedIn Company Page & Personal Branding", "Instagram Growth Strategy (Feed, Stories, Reels)",
    "Twitter / X Growth & Engagement", "Facebook Group Management & Community Building",
    "TikTok Viral Content Strategy", "YouTube Channel Optimization & Community",
    "Short-Form Video Production (Reels, TikTok, Shorts)", "Social Listening & Sentiment Analysis",
    "Brand Reputation & Crisis Monitoring", "Influencer Marketing Management", "Key Opinion Leader (KOL) Outreach",
    "Influencer Campaign ROI Tracking", "User-Generated Content (UGC) Sourcing",
    "Discord Server Community Building", "Reddit Community Engagement & AMAs",
    "Social Media Schedulers (Buffer, Hootsuite, Sprout Social, Later)", "Canva Pro for Social Media",
    // Email Marketing & Lifecycle Automation
    "Email Marketing Strategy", "Customer Lifecycle Marketing", "Drip Campaign Architecture",
    "Newsletter Curation & Publishing", "Email Deliverability Optimization", "Sender Score & Domain Reputation",
    "Email Authentication (DKIM, SPF, DMARC)", "Subscriber List Segmentation", "Email A/B Testing (Subject Lines, Preview Text)",
    "Click-Through Rate (CTR) Optimization", "Open Rate Optimization", "Unsubscribe Rate & Spam Complaint Reduction",
    "Behavior-Triggered Automation Workflows", "HubSpot Marketing Hub Administration",
    "Marketo Engage Administration", "Mailchimp Marketing Platform", "Klaviyo E-Commerce Automation",
    "ActiveCampaign Workflows", "SendGrid Email API", "Brevo (Sendinblue)", "Salesforce Marketing Cloud",
    "ConvertKit for Creators", "Customer.io Event-Driven Messaging",
    // Marketing Analytics, Tracking & CRO
    "Marketing Analytics & Reporting", "Google Analytics 4 (GA4) Implementation", "Google Tag Manager (GTM) Container Setup",
    "UTM Parameter Tracking Frameworks", "Multi-Touch Marketing Attribution", "First-Touch vs. Last-Touch Attribution",
    "Linear & Time-Decay Attribution Models", "Customer Lifetime Value (CLV / LTV)", "Customer Acquisition Cost (CAC)",
    "Return on Ad Spend (ROAS)", "Return on Marketing Investment (ROMI)", "Conversion Rate Optimization (CRO)",
    "Landing Page AB Testing (Unbounce, Instapage)", "Heatmap & User Behavior Analysis (Hotjar, Crazy Egg)",
    "Click-Tracking & Scroll-Depth Tracking", "Predictive Lead Scoring Models", "Sales-Marketing Funnel Alignment",
    // Public Relations (PR), Events & Partnerships
    "Public Relations (PR) Campaign Management", "Media Relations & Journalist Pitching",
    "Crisis Communications Strategy", "Press Release Wire Distribution", "Virtual Event & Webinar Hosting (Zoom, ON24)",
    "Trade Show & Conference Event Marketing", "Event Sponsorship Negotiation", "Brand Podcast Hosting & Distribution",
    "Affiliate Marketing Network Management (ShareASale, CJ, Impact)", "Co-Marketing Partnership Campaigns",
    "Customer Advocacy & Referral Programs"
  ],

  "Sales & Business Development": [
    // Core Sales Methodologies & Enterprise Sales
    "B2B Enterprise Sales", "B2C Sales Management", "Solution Selling Methodology", "Consultative Selling Approach",
    "Inbound Sales Qualification", "Outbound Cold Outreach", "Inside Sales Operations", "Field Sales & On-Site Pitches",
    "Account-Based Marketing (ABM)", "Account-Based Selling (ABS)", "The Challenger Sale Methodology",
    "SPIN Selling (Situation, Problem, Implication, Need-Payoff)", "MEDDIC & MEDDPICC Sales Framework",
    "BANT Qualification (Budget, Authority, Need, Timeline)", "Value-Based Selling", "Strategic Account Management",
    "Sales Pipeline Architecture & Management", "Sales Revenue Forecasting", "Quota Attainment Strategy",
    "Territory Planning & Account Allocation", "Sales Strategy Formulation", "High-Velocity Sales",
    "Complex Deal Multi-Threading", "Economic Buyer Engagement", "Champion Building within Accounts",
    // Prospecting, Outreach & Lead Generation
    "Lead Generation Strategy", "B2B Prospecting Techniques", "Cold Calling Mastery", "Cold Email Crafting",
    "Social Selling on LinkedIn", "LinkedIn Sales Navigator Mastery", "Discovery Call Facilitation",
    "Lead Qualification & Scoring", "Inbound Lead Routing & Response Time Optimization",
    "Prospect List Building & Data Enrichment", "ZoomInfo Platform", "Apollo.io Platform",
    "Lusha Contact Intelligence", "Cognism B2B Data", "Hunter.io Email Finder", "LeadIQ Platform",
    "Clearbit Enrichment", "Seamless.ai Search", "Sales Cadence & Sequencing Automation",
    "Outreach.io Platform", "Salesloft Platform", "Lemlist Cold Outreach", "Woodpecker Automation",
    // Sales Pitches, Demos & Closing
    "Product Demonstration & Discovery", "Value-Driven Sales Presentations", "Pitch Deck Customization & Delivery",
    "Executive C-Suite Pitching (CEO, CTO, CFO, CMO)", "Objection Handling & Reframing",
    "Active Listening in Sales", "Principled Negotiation (Getting to Yes)", "Price & Discounting Strategy",
    "Contract Closing Techniques", "Closing Large Enterprise Deals ($100k+ ARR)", "RFP (Request for Proposal) Management",
    "RFI (Request for Information) Responses", "Statement of Work (SOW) Scoping", "Mutual Action Plans (MAP)",
    "Commercial Proposal Writing", "Sales Contract Terms & Redlining",
    // CRM Administration & Sales Tech
    "CRM System Administration", "Salesforce Sales Cloud Mastery", "Salesforce Lightning Interface",
    "Salesforce Process Builder & Flows", "HubSpot Sales Hub CRM", "Pipedrive CRM", "Zoho CRM Platform",
    "Microsoft Dynamics 365 Sales", "Freshsales CRM", "Copper CRM for Google Workspace",
    "Sales Pipeline Hygiene & Inspection", "CRM Data Integrity & Deduplication", "Sales Activity Logging & Tracking",
    "Sales Dashboards & Performance Reports", "Gong.io Conversation Intelligence", "Chorus.ai Call Coaching",
    // Account Management, Upselling & Customer Success
    "Key Account Management (KAM)", "Client Relationship Management", "Customer Retention Strategy",
    "Account Expansion Strategy", "Cross-Selling & Upselling Workflows", "Client Onboarding & Kickoff",
    "Quarterly Business Reviews (QBR) Leadership", "Annual Contract Renewal Negotiations",
    "Net Retention Rate (NRR) Optimization", "Gross Retention Rate (GRR) Optimization", "Customer Health Score Monitoring",
    "Early Warning Churn Indicators", "Customer Advocacy & Case Study Enlistment", "Executive Sponsorship Programs",
    // Business Development & Strategic Alliances
    "Strategic Partnerships Formation", "Channel Sales & Distribution", "Value-Added Reseller (VAR) Management",
    "Co-Selling with Cloud Hyperscalers (AWS, Azure, GCP)", "System Integrator (SI) Partnerships",
    "Joint Venture Deal Structuring", "OEM Partnership Negotiations", "Affiliate Channel Strategy",
    "Market Expansion & International Sales", "Cross-Border Commercial Agreements", "Mergers & Acquisitions (M&A) Origination",
    "Deal Structuring & Term Sheets", "Intellectual Property Licensing", "Contract Negotiations & Legal Alignment",
    // Revenue Operations (RevOps) & Sales Enablement
    "Revenue Operations (RevOps)", "Sales Enablement Program Design", "Sales Coaching & Rep Mentoring",
    "Sales Playbook Authoring", "Sales Compensation Plan Design", "Commission Tracking Software (CaptivateIQ, Spiff)",
    "Sales Incentive Contests (SPIFs)", "Sales Collateral Management (Highspot, Seismic)", "Win/Loss Analysis",
    "Sales Ramp Time Reduction", "Sales-Marketing SLA Alignment", "Cross-Functional Collaboration with Product Teams"
  ],

  "Finance & Accounting": [
    // Financial Accounting & Bookkeeping
    "Financial Accounting Principles", "General Ledger (GL) Management", "Bookkeeping Fundamentals",
    "Chart of Accounts (COA) Design", "Double-Entry Accounting System", "Journal Entries & Month-End Accruals",
    "Adjusting Journal Entries", "Trial Balance Preparation & Review", "Bank Account Reconciliation",
    "Credit Card Reconciliation", "Intercompany Account Reconciliations", "Accounts Payable (AP) Operations",
    "Invoice Verification & 3-Way Matching", "Vendor Payment Processing (ACH, Wire, Check)", "Form 1099 Reporting",
    "Accounts Receivable (AR) Operations", "Customer Invoicing & Billing", "Collections & Accounts Aging Management",
    "Credit Risk Assessment & Credit Limits", "Allowance for Doubtful Accounts", "Petty Cash Management",
    "Fixed Asset Accounting & Depreciation Schedules", "Amortization of Intangible Assets",
    "Accrual Accounting Method", "Cash-Basis Accounting Method", "Prepaid Expenses Amortization",
    // Financial Reporting, Compliance & Standards
    "Financial Statement Preparation", "Balance Sheet Statement Analysis", "Income Statement (P&L) Analysis",
    "Cash Flow Statement Analysis (Direct & Indirect)", "Statement of Shareholders' Equity",
    "US GAAP (Generally Accepted Accounting Principles)", "IFRS (International Financial Reporting Standards)",
    "Revenue Recognition Standards (ASC 606 / IFRS 15)", "Lease Accounting Standards (ASC 842 / IFRS 16)",
    "Stock-Based Compensation Accounting (ASC 718)", "SEC Filings & Compliance (Form 10-K, 10-Q, 8-K)",
    "Management Discussion & Analysis (MD&A)", "Consolidated Financial Statements", "Multi-Currency Translation (ASC 830)",
    "Segment Reporting", "Audited Financial Statements Preparation",
    // Corporate Finance, FP&A & Budgeting
    "Financial Planning & Analysis (FP&A)", "Annual Operating Budget (AOP)", "Zero-Based Budgeting (ZBB)",
    "Rolling Financial Forecasts", "Variance Analysis (Budget vs. Actual / BvA)", "Cost Center Allocation",
    "Capital Expenditure (CapEx) Analysis", "Operating Expenditure (OpEx) Optimization", "Working Capital Optimization",
    "Cash Flow Forecasting & Liquidity Planning", "Burn Rate & Cash Runway Modeling",
    "Scenario Analysis & Stress Testing", "Financial Modeling in Microsoft Excel", "Three-Statement Integrated Model",
    "Discounted Cash Flow (DCF) Valuation", "Internal Rate of Return (IRR) Calculation", "Net Present Value (NPV) Analysis",
    "Payback Period Analysis", "Cost of Capital (WACC Calculation)", "Cost-Volume-Profit (CVP) Analysis",
    "Break-Even Point Calculation", "Gross Margin & Contribution Margin Analysis", "Unit Economics in SaaS",
    "Annual Recurring Revenue (ARR) Metrics", "Monthly Recurring Revenue (MRR) Metrics", "Customer Churn Financial Impact",
    // Tax Planning & Corporate Tax Compliance
    "Corporate Income Tax Preparation (Form 1120/1120-S)", "Tax Planning & Minimization Strategies",
    "Indirect Tax Compliance (GST, VAT)", "State and Local Tax (SALT) Compliance", "US Sales & Use Tax Compliance (Avalara)",
    "Transfer Pricing Documentation (OECD Guidelines)", "R&D Tax Credit Calculation", "Withholding Tax (TDS / W-8BEN)",
    "Tax Audit Defense & Representation", "Deferred Tax Assets (DTA) & Liabilities (DTL)",
    "Cross-Border International Tax Treaties", "Excise Tax Compliance",
    // Audit, Internal Controls & Risk Management
    "Internal Audit Methodologies", "External Audit Coordination (Big 4 & Mid-Tier)", "Sarbanes-Oxley (SOX 404) Compliance",
    "COSO Internal Control Framework", "Segregation of Duties (SoD)", "Fraud Risk Assessment & Forensic Accounting",
    "Compliance Audit Programs", "Enterprise Risk Management (ERM)", "Financial Risk Hedging Strategies",
    "Foreign Exchange (FX) Risk Management", "Interest Rate Swap Management", "Credit Risk Evaluation Models",
    "Statutory Regulatory Reporting", "AML (Anti-Money Laundering) Compliance in Finance",
    // Investment Banking, M&A & Private Equity
    "Corporate Business Valuation", "Comparable Company Analysis (Trading Comps)", "Precedent Transactions Analysis",
    "Mergers & Acquisitions (M&A) Execution", "Financial Due Diligence (Buy-Side & Sell-Side)",
    "Quality of Earnings (QoE) Reporting", "Post-Merger Financial Integration", "Private Equity (PE) LBO Modeling",
    "Venture Capital (VC) Due Diligence", "Term Sheet Financial Analysis", "Cap Table Management (Carta, Pulley)",
    "Debt Financing & Credit Facilities", "Syndicated Loan Facilities", "Corporate Treasury Operations",
    "Commercial Bank Relationship Management", "Initial Public Offering (IPO) Readiness", "Investor Relations (IR) Reporting",
    // Accounting Software, Tools & ERPs
    "Advanced Microsoft Excel (VLOOKUP, INDEX/MATCH, XLOOKUP, Nested IFs)", "Excel Pivot Tables & Power Pivot",
    "Excel Macros & VBA Automation", "Google Sheets Financial Functions", "QuickBooks Online & Desktop",
    "Xero Accounting Software", "Tally Prime & Tally.ERP 9", "SAP ERP Financials (SAP FICO / S/4HANA)",
    "Oracle NetSuite ERP", "Workday Financial Management", "Microsoft Dynamics 365 Finance", "Sage Intacct Cloud Financials",
    "Zoho Books Accounting", "Bill.com Accounts Payable", "Expensify & Concur Expense Management",
    "Ramp & Brex Corporate Cards Management", "BlackLine Financial Close Management", "Anaplan Connected Planning",
    "Adaptive Planning (Workday)", "Tipalti Global Payables"
  ],

  "HR & People Operations": [
    // Talent Acquisition & Executive Search
    "Talent Acquisition Strategy", "Technical Recruiting (Engineering, Product, Data)", "Executive Search & Headhunting",
    "Full-Cycle Recruiting Process", "Candidate Sourcing Strategies", "Advanced Boolean Search Syntax",
    "LinkedIn Recruiter Advanced Tools", "Job Description Crafting & Optimization", "Candidate Screening & Assessment",
    "Behavioral Interviewing (STAR Method)", "Competency-Based Interview Design", "Structured Interview Frameworks",
    "Interview Scheduling & Candidate Logistics", "Candidate Experience (CX) Optimization", "Job Offer Negotiation & Closing",
    "Pre-Employment Background Checks", "Reference Checking Protocols", "University & Campus Recruiting",
    "Internship & Co-op Program Management", "Diversity, Equity & Inclusion (DEI) Talent Sourcing",
    "Employer Branding & EVP (Employee Value Proposition)", "Recruitment Marketing Campaigns",
    "Glassdoor & Indeed Company Profile Management", "Employee Referral Program Administration",
    "Applicant Tracking Systems (ATS) Administration", "Greenhouse ATS", "Lever ATS", "Workday Recruiting Module",
    "BambooHR ATS", "JazzHR Platform", "SmartRecruiters ATS", "iCIMS Talent Cloud", "Ashby ATS",
    // Onboarding, Culture & Employee Experience
    "Employee Onboarding Experience", "New Hire Orientation Program Design", "First 30-60-90 Days Plan Formulation",
    "Remote & Distributed Employee Onboarding", "Offboarding Protocols & Knowledge Transfer", "Exit Interview Facilitation & Analysis",
    "Corporate Alumni Network Management", "Employee Engagement Survey Design", "Employee Pulse Surveys (Culture Amp, Lattice)",
    "Employee Net Promoter Score (eNPS) Strategy", "Company Culture & Values Integration", "Internal Communications Strategy",
    "Employee Recognition & Awards Programs", "Workplace Mental Health & Wellbeing Initiatives",
    "Virtual & In-Person Team Building Events", "Employee Resource Groups (ERGs) Sponsorship",
    // Performance Management & Organizational Development
    "Performance Management Frameworks", "Annual & Bi-Annual Performance Reviews", "360-Degree Feedback Processes",
    "Goal Setting & OKR Alignment", "Continuous Performance Feedback Culture", "Performance Improvement Plan (PIP) Management",
    "Succession Planning Frameworks", "9-Box Grid Talent Reviews", "High-Potential (HiPo) Identification",
    "Learning & Development (L&D) Strategy", "Training Needs Analysis (TNA)", "Instructional Design & Course Creation",
    "Leadership & Manager Coaching Programs", "First-Time Manager Training", "Career Progression Frameworks & Ladders",
    "Skills Gap Analysis & Upskilling", "Learning Management Systems (LMS)", "Cornerstone OnDemand LMS",
    "Docebo LMS", "TalentLMS Platform", "LinkedIn Learning for Enterprise", "Skillsoft Percipio",
    // Total Rewards: Compensation, Equity & Benefits
    "Total Rewards Strategy", "Compensation Benchmarking & Market Pricing", "Option Impact / Pave Compensation Data",
    "Radford Global Compensation Surveys", "Salary Banding & Grade Level Structures", "Variable Pay & Bonus Plan Design",
    "Sales Commission Incentive Plans", "Equity Administration (Stock Options, RSUs, ESPP)", "Carta Cap Table & Equity Tool",
    "Employee Health & Dental Benefits Administration", "Retirement & 401(k) / Pension Plan Management",
    "Voluntary Wellness Benefits Administration", "Paid Time Off (PTO) & Leave Policy Design",
    "FMLA (Family and Medical Leave Act) Administration", "Parental Leave Programs", "Pay Equity Analysis & Audits",
    // Labor Laws, Employee Relations & HR Compliance
    "Employee Relations & Conflict Resolution", "Workplace Mediation & Grievance Procedures",
    "Internal Workplace Investigations", "Progressive Disciplinary Action Procedures", "HR Policy & SOP Development",
    "Employee Handbook Authoring & Updating", "Federal, State & Local Employment Law Compliance",
    "Equal Employment Opportunity (EEO) Compliance", "Americans with Disabilities Act (ADA) Accommodations",
    "OSHA Workplace Safety & Health Standards", "Fair Labor Standards Act (FLSA) Wage & Hour",
    "Independent Contractor vs. Employee Classification (W-2 vs. 1099)", "US Immigration & Visa Sponsorship (H-1B, L-1, TN, PERM)",
    "Global Mobility & Expatriate Relocation", "Labor Union Negotiations & Collective Bargaining",
    "Involuntary Terminations & Severance Agreements", "Worker Adjustment and Retraining Notification (WARN Act)",
    // HRIS Systems & People Analytics
    "HR Information System (HRIS) Administration", "Workday HCM (Human Capital Management)",
    "BambooHR Core System", "Gusto Payroll & HR", "Rippling Unified HR Platform", "Zenefits HR Platform",
    "ADP Workforce Now System", "Paychex Flex", "SAP SuccessFactors Suite", "People Analytics & Workforce Insights",
    "Headcount Planning & Budgeting", "Employee Turnover & Retention Rate Metrics", "Time-to-Hire & Cost-per-Hire Tracking",
    "HR Dashboards & Executive Reporting", "HR Automation & Workflow Digitization"
  ],

  "Core / Mechanical Engineering": [
    // CAD, 3D Modeling & Drafting
    "Computer-Aided Design (CAD)", "3D Parametric Modeling", "2D Engineering Drafting & Detailing",
    "Engineering Drawings Interpretation", "Dassault Systèmes SolidWorks", "Autodesk AutoCAD",
    "Autodesk Inventor", "Autodesk Fusion 360", "Dassault Systèmes CATIA V5/V6", "PTC Creo (Pro/ENGINEER)",
    "Siemens NX (Unigraphics)", "Solid Edge CAD", "Rhino 3D Modeling", "Onshape Cloud CAD",
    "Geometric Dimensioning and Tolerancing (GD&T)", "ASME Y14.5 Standard Application", "ISO Geometrical Product Specifications (GPS)",
    "Tolerance Stack-Up Analysis (Worst-Case, RSS)", "Bill of Materials (BOM) Generation", "Product Data Management (PDM)",
    "Product Lifecycle Management (PLM)", "Siemens Teamcenter PLM", "PTC Windchill PLM", "Dassault Enovia PLM",
    // CAE, Finite Element Analysis (FEA) & Simulation
    "Computer-Aided Engineering (CAE)", "Finite Element Analysis (FEA)", "ANSYS Mechanical Simulation",
    "ANSYS Fluent CFD", "ANSYS CFX", "Abaqus FEA Suite", "COMSOL Multiphysics", "Altair HyperMesh Preprocessing",
    "MSC Nastran / Patran", "LS-DYNA Explicit Dynamics", "Computational Fluid Dynamics (CFD)",
    "Aerodynamics & Drag Simulation", "Structural Static Stress Analysis", "Dynamic & Transient Analysis",
    "Modal & Vibration Analysis", "Harmonic Response Analysis", "Fatigue Life & Durability Prediction",
    "Thermal & Heat Transfer Analysis (Conduction, Convection, Radiation)", "Thermal Stress Analysis",
    "Multibody Dynamics (MBD / MSC Adams)", "Noise, Vibration, and Harshness (NVH) Testing",
    "Crashworthiness & Impact Simulation", "Turbulence Modeling (k-epsilon, k-omega, LES)",
    // Manufacturing Processes & Production Technology
    "Manufacturing Engineering Fundamentals", "Computer-Aided Manufacturing (CAM)", "Mastercam Programming",
    "Autodesk Fusion 360 CAM", "CNC Machining (3-Axis, 4-Axis, 5-Axis)", "CNC G-Code & M-Code Programming",
    "Milling Machine Operations", "CNC Lathe & Turning Operations", "Sheet Metal Design & Fabrication",
    "Welding Technologies (TIG, MIG, Stick, Laser, Spot)", "Plastic Injection Molding Tooling Design",
    "High-Pressure Die Casting", "Sand Casting & Investment Casting", "Hot & Cold Forging Processes",
    "Metal Extrusion Techniques", "Additive Manufacturing (3D Printing - FDM, SLA, SLS, DMLS)",
    "Surface Finishing, Anodizing & Powder Coating", "Heat Treatment of Metals (Quenching, Tempering, Annealing)",
    "Rapid Prototyping Techniques", "Design for Manufacturing (DFM)", "Design for Assembly (DFA)",
    "Design for Six Sigma (DFSS)", "Failure Mode and Effects Analysis (FMEA)", "Design FMEA (DFMEA)",
    "Process FMEA (PFMEA)", "Poka-Yoke (Mistake Proofing)",
    // Thermodynamics, Fluid Power & HVAC
    "Classical Thermodynamics", "Applied Engineering Thermodynamics", "Fluid Mechanics & Hydrodynamics",
    "Hydraulics & Fluid Power Systems", "Hydraulic Cylinder & Valve Sizing", "Pneumatic Circuit Design",
    "Pneumatic Actuators & Regulators", "HVAC System Design (Commercial & Industrial)",
    "Vapor Compression Refrigeration Cycles", "Psychrometric Chart Analysis", "ASHRAE Standards Compliance",
    "Ductwork Sizing & Airflow Balancing", "Piping and Instrumentation Diagrams (P&ID)",
    "Industrial Piping Design (AutoCAD Plant 3D, Caesar II)", "Pipe Stress Analysis",
    "Industrial Pump Sizing & Selection (Centrifugal, Positive Displacement)", "Air Compressor Systems",
    "Heat Exchanger Design (Shell and Tube, Plate Frame)", "Boilers & Steam Generation Systems",
    "Power Generation Systems (Gas Turbines, Steam Turbines)", "Renewable Energy Systems (Solar Thermal, Wind Turbines)",
    "Internal Combustion Engines (Otto & Diesel Cycles)", "Electric Vehicle (EV) Powertrain Design",
    "Battery Thermal Management Systems (BTMS)", "Vehicle Dynamics & Suspension Tuning",
    // Materials Engineering & NDT Testing
    "Materials Science & Engineering", "Metallurgy & Phase Diagrams (Iron-Carbon Diagram)",
    "Ferrous Metals & Alloy Steels", "Non-Ferrous Metals (Aluminum, Titanium, Copper Alloys)",
    "Engineering Plastics & Polymers Selection", "Fiber-Reinforced Composite Materials", "Engineering Ceramics",
    "Mechanical Tensile Testing (ASTM E8 Standards)", "Hardness Testing (Rockwell, Brinell, Vickers)",
    "Charpy & Izod Impact Testing", "Creep & Rupture Testing", "Non-Destructive Testing (NDT) Methods",
    "Ultrasonic Testing (UT)", "Magnetic Particle Testing (MT)", "Liquid Dye Penetrant Testing (PT)",
    "Radiographic X-Ray Testing (RT)", "Eddy Current Testing (ET)", "Visual Weld Inspection (CWI)",
    "Corrosion Engineering & Cathodic Protection", "Tribology (Friction, Wear, and Lubrication)",
    // Mechatronics, Robotics & Automation
    "Mechatronics System Design", "Industrial Robotics Engineering", "Kinematics & Dynamics of Linkages",
    "Industrial Automation & Control", "Programmable Logic Controllers (PLC)", "Siemens SIMATIC S7-1200 / S7-1500",
    "Allen-Bradley / Rockwell ControlLogix", "PLC Ladder Logic Programming", "Structured Text (ST) Programming",
    "SCADA System Architecture", "Human-Machine Interface (HMI) Programming", "Sensors Selection (Proximity, Optical, Pressure, Encoders)",
    "Actuators Selection (Pneumatic, Hydraulic, Electric)", "Servo Drives & Stepper Motor Control",
    "Industrial Robotic Arms (KUKA, ABB, Fanuc, Yaskawa)", "Robot Operating System (ROS / ROS2)",
    "Embedded Control Algorithms (PID Tuning)", "Microcontroller Interfacing for Automation",
    // Quality Control, Lean & Plant Operations
    "Quality Control (QC) Inspection", "Quality Assurance (QA) Frameworks", "Lean Manufacturing Principles",
    "Six Sigma Methodologies (Green Belt / Black Belt)", "DMAIC Problem-Solving Process",
    "5S Workplace Organization System", "Kaizen Continuous Improvement", "Value Stream Mapping (VSM)",
    "Statistical Process Control (SPC)", "Control Charts (X-bar and R Charts)", "Process Capability Analysis (Cp, Cpk)",
    "Measurement System Analysis (MSA / Gage R&R)", "Root Cause Corrective Action (RCCA)",
    "8D Problem Solving Process", "ISO 9001 Quality Management Systems", "IATF 16949 Automotive Quality Standard",
    "ISO 14001 Environmental Management", "Industrial Plant Layout & Optimization",
    "Preventive & Predictive Maintenance (PdM)", "Total Productive Maintenance (TPM)",
    "Industrial Safety & Ergonomics", "OSHA Machine Guarding Standards", "PPE Compliance in Manufacturing"
  ]
};

const outputPath = path.join(__dirname, "domainSkillsData.json");
fs.writeFileSync(outputPath, JSON.stringify(domainSkillsData, null, 2), "utf8");

let totalSkills = 0;
console.log("Domain breakdown:");
for (const [domain, list] of Object.entries(domainSkillsData)) {
  console.log(`- ${domain}: ${list.length} skills`);
  totalSkills += list.length;
}
console.log(`\nTotal skills written to domainSkillsData.json: ${totalSkills}`);
